---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: This Stack will use resources from StackA
Parameters:
  DDBStack:
    Description: This is the DynamoDB StackA that we're dependent upon for DDB ARN & TableName values
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: StackNONE
  DDBPasswd:
    AllowedPattern: "^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])(?=.*[!@#$%_]).*$"
    NoEcho: true
    Description: This is an example of a password passed in at stack deployment. Not used anywhere but shows that NoEcho prevents the password from being shown by using a describe-stacks CLI
    MaxLength: 50
    MinLength: 9
    Type: String
    
Resources:
  QueryTable:
    Type: AWS::Serverless::Function
    DependsOn: LambdaExecAndDDBQueryRole
    Properties:
      CodeUri: ./lambdaCode
      Handler: index.handler
      Runtime: nodejs6.10
      Role: !GetAtt LambdaExecAndDDBQueryRole.Arn
      Environment:
        Variables:
            TABLE_NAME:
              Fn::ImportValue: 
                !Sub ${DDBStack}-DDBTableName
            SOME_PASSWORD:
              Ref: DDBPasswd

  LambdaExecAndDDBQueryRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: cloudwatch
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: !Join
              - ''
              - - 'arn:aws:logs:'
                - !Ref 'AWS::Region'
                - ':'
                - !Ref 'AWS::AccountId'
                - ':*'
      - PolicyName: ddbquery
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - dynamodb:Query
            Resource: !ImportValue StackA-DDBTableARN