AWSTemplateFormatVersion: "2010-09-09"
Description: "This Stack simply creates a DynamoDB Table for another Stack to use via 'Cross Stack References'"
Resources: 
  myDynamoDBTable: 
    Type: "AWS::DynamoDB::Table"
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "userId"
          AttributeType: "S"
        - 
          AttributeName: "objectId"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "userId"
          KeyType: "HASH"
        - 
          AttributeName: "objectId"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "2StacksExampleTable"
Outputs:
  DDBTableARN:
    Description: ARN of the DDB table
    Value: !GetAtt myDynamoDBTable.Arn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-DDBTableARN
  DDBTableName:
    Description: Name of the DDB table
    Value: !Ref myDynamoDBTable
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-DDBTableName
    